use crate::detect::VersionToTag;

/// Use `gh` to create the versions in GitHub.
///
/// Versions must be piped to STDIN in the YAML format generated by the `detect` subcommand.
#[derive(clap::Args)]
pub struct CreateReleases {
    /// Print the `gh` commands instead of running them.
    #[arg(long, action)]
    dry_run: bool,
}

impl CreateReleases {
    pub fn create_releases_from_versions(
        &self,
        mut versions: Vec<VersionToTag>,
    ) -> anyhow::Result<()> {
        versions.sort_by_key(|version| version.created_at);
        // println!("{:?}", versions);
        for version in versions.into_iter() {
            let VersionToTag {
                version: _,
                tagname,
                commit_hash,
                created_at: _,
                title,
                notes,
            } = &version;
            let mut cmd = std::process::Command::new("gh");
            cmd.args(["release", "create", tagname]);
            cmd.args(["--target", commit_hash]);
            cmd.args(["--title", title]);
            cmd.args(["--notes", notes]);
            if self.dry_run {
                println!("{:?}", cmd);
            } else {
                tracing::info!(tagname = tagname, title = title, "Creating version with gh");
                cmd.spawn()?.wait()?;
            }
        }
        Ok(())
    }
}
